APPLICATION = ln18
BOARD ?= calliope-mini
RIOTBASE ?= $(CURDIR)/../../..

FEATURES_REQUIRED = periph_pwm

USEMODULE += xtimer
USEMODULE += nrfmin
USEMODULE += gnrc_netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += ps

include $(RIOTBASE)/Makefile.include
