APPLICATION = ln18
BOARD ?= nrf52dk
RIOTBASE ?= $(CURDIR)/../../..

USEMODULE += xtimer
USEMODULE += nrfmin
USEMODULE += gnrc_netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += ps
USEMODULE += srf04

include $(RIOTBASE)/Makefile.include
